# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author:
  name: Bence Monus
  handle: cromega

title: The Î± and the cromega
email: crome@moronia.hu
description: This is where I rant about things.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://alphaandthecromega.sublimia.nl" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year/:month/:day/:title

liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: true

# Build settings
markdown: kramdown
timezone: Europe/London
excerpt_separator: "<!-- more -->"

sass:
  style: compact

collections:
  about_pages:
    output: true
    permalink: /about/:name

exclude:
- bin
- Gemfile*
- LICENSE.md
- README.md
- nginx.conf
- Dockerfile
- lib
- spec
- vendor/
