resources:
- name: blog
  type: git
  source:
    uri: git@github.com:cromega/blorg
    private_key: {{deploy-key}}
    submodules: all
- name: blog-deps
  type: git
  source:
    uri: git@github.com:cromega/blorg
    private_key: {{deploy-key}}
    paths: [Gemfile.lock, Dockerfile.ci]
- name: ci-image
  type: docker-image
  source:
    repository: cromega/blog-ci
    username: cromega
    password: {{dockerhub-password}}
- name: image
  type: docker-image
  source:
    repository: cromega/blog
    username: cromega
    password: {{dockerhub-password}}

jobs:
- name: ci-image
  serial_groups: [ci-image-build]
  plan:
  - get: blog-deps
    trigger: true
  - put: ci-image
    params:
      build: blog-deps/
      dockerfile: blog-deps/Dockerfile.ci
- name: build
  serial_groups: [ci-image-build]
  plan:
  - get: blog
    trigger: true
  - task: build
    file: blog/ci/build.yml
  - put: image
    params:
      build: blog-rendered/
