resources:
- name: blog
  type: git
  source:
    uri: git@github.com:cromega/blorg
    private_key: {{deploy-key}}
    submodules: all
- name: blog-deps
  type: git
  source:
    uri: git@github.com:cromega/blorg
    private_key: {{deploy-key}}
    paths: [Gemfile.lock, Dockerfile.ci]
- name: ci-image
  type: docker-image
  source:
    repository: cromega/blog-ci
    username: cromega
    password: {{dockerhub-password}}
- name: image
  type: docker-image
  source:
    repository: cromega/blog
    username: cromega
    password: {{dockerhub-password}}
- name: kube
  type: kubernetes
- name: kubeconfig
  type: s3
  source:
    bucket: sublimia-ci-bucket-platform
    versioned_file: k3s.yml
    access_key_id: {{ci-access-key-id}}
    secret_access_key: {{ci-secret-access-key}}
    region_name: eu-west-1

jobs:
- name: ci-image
  serial_groups: [ci-image-build]
  plan:
  - get: blog-deps
    trigger: true
  - put: ci-image
    params:
      build: blog-deps/
      dockerfile: blog-deps/Dockerfile.ci
- name: build
  serial_groups: [ci-image-build]
  plan:
  - get: blog
    trigger: true
  - task: build
    file: blog/ci/build.yml
  - put: image
    params:
      build: blog-rendered/
- name: deploy
  plan:
  - in_parallel:
    - get: blog
      trigger: true
      passed: [build]
    - get: kubeconfig
  - put: kube
    params:
      kubectl: apply -f blog/ci/k8s/deployment.yml -f blog/ci/k8s/service.yml -f blog/ci/k8s/ingress.yml
      namespace: sublimia
      kubeconfig_file: kubeconfig/k3s.yml
      wait_until_ready: 0
  - put: kube
    params:
      kubectl: patch deploy blog -p '{"spec":{"template":{"metadata":{"labels":{"updated_at":"'$(date +%s)'"}}}}}'
      namespace: sublimia
      kubeconfig_file: kubeconfig/k3s.yml
      wait_until_ready_selector: app=blog

resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.17"
