name: DockerImage

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ruby:2.7.1
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Build pages
        run: |
          bundle install
          bundle exec jekyll build
      - name: Save output
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site

  image:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Download output
        uses: actions/download-artifact@v2
        with:
          name: site
          path: _site
      - name: Docker login
        env:
          DOCKERHUB_PW: ${{ secrets.dockerhub_password }}
        run: echo "$DOCKERHUB_PW" | docker login -u cromega --password-stdin
      - name: Push image
        run: |
          docker build -t cromega/blorg .
          docker push cromega/blorg

  trigger-deploy:
    needs: [image]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        env:
          TOKEN: ${{ secrets.repo_token }}
        run: |
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            https://api.github.com/repos/cromega/sublimia-platform/dispatches \
            --data '{"event_type":"deploy:blorg"}'
